language: python
dist: bionic
sudo: false
cache:
  pip: true
  directories:
    - $HOME/.cache/pre-commit
before_install:
- >
  pip install --upgrade pip mypy 'attrs==19.2.0'
  -r https://raw.githubusercontent.com/aws-cloudformation/aws-cloudformation-rpdk/master/requirements.txt
install:
- pip install . src/
env:
  global:
  - AWS_DEFAULT_REGION="us-east-1"
script:
- pre-commit run --all-files
jobs:
  include:
  - python: "3.6"
  - python: "3.7"
  - python: "3.8"
  - stage: "integ python 3.6"
    language: python
    python: "3.6"
    script:
      - ls -la
      - DIR=$(mktemp -d)
      - cd "$DIR"
      - ls -la
      - printf "AWS::Foo::Bar\n1\ny" | cfn init -vv
      - ls -la
      - mypy src/aws_foo_bar/ --strict --implicit-reexport
  - stage: "integ python 3.7"
    language: python
    python: "3.7"
    script:
      - DIR=$(mktemp -d)
      - cd "$DIR"
      - ls -la
      - printf "AWS::Foo::Bar\n2\ny" | cfn init -vv
      - ls -la
      - mypy src/aws_foo_bar/ --strict --implicit-reexport
  - stage: deploy
    python: "3.8"
    script:
      - cd $(bash before_deploy.sh)
    deploy:
      provider: pypi
      user: aws-cloudformation-developers
      password:
        secure: "U1khJN3N7HYbMfUfkRJtMV3jgJGJJulHzkUOQjHiRJ+su+C+zqxpU2xt/sfDrR5rJ44O6aKEvj72QTWUqqzeHjnAzhvCFbMdyvVpE1mXFqasfeNXBDLNRlofqqkwhWen/K2oZ2+e9lR0/Ej/WFQrEePZpaTGwKHMvqrvH0DeiiMF7jtPFUC9M5aGuIOmKL70F+LD3Nh3jMsczcdnu88kUPNyOLnI7jPC4SxITAkjAAym2SGMWFaMQKEg/Esic/ckwe23G417ek0cVhaQs8lC49pTm6eZvLKIfOY1x+pE67G9CAqbJnAJRLlDfgRge/OuqkDcYG+euVzpsB+/iYyw+My7u7FHd0gQUhsMkRjpNkzgMM0FlTI+P42ahhwMzsuKG7eiTBMvrDLDmwsC9sL8hSl/NjtWadaOYtbsJMGzjqBqcfNNDC0hC8KHNC+Ti1IYfINt1iR/Gnr8yxmjwRkzvhbZxwgKjcaCfngRao4eNHn3T6zP/k8jueiG3oozLTHwaS55G0LCDpr8Hi5ACO5lZRKnrTQHYSTEqJQLXfqrfREA8NKRi8Cu2LSZID0VFfWfuXFY9kVn+uPjYCsJQ1jOatbE9OdWRevIyHSuV2l6B4U7BJQ0KWIG77e22DkjNOk8hZxOgsJG2k5w8vMTRR5wYHufQuX/naBSLAwhUZq5LA0="
      distributions: sdist bdist_wheel
      on:
        tags: true
